RAW_OUTPUT_FOLDER = "raw_outputs"
CLEAN_OUTPUT_FOLDER = "clean_outputs"
ARCHIVE_ROOT_FOLDER = "snapshots"
SNAPSHOT_INDEX_FILE = "snapshot_index.json"
CLEAN_SCHEMA_VERSION = "schema-v1"
PIPELINE_VERSION = "archive-enabled-v1"

MASTER_COLUMNS = [
    "Project ID",
    "ISO",
    "Status",
    "Queue Date",
    "Withdrawn Date",
    "Proposed Date",
    "State",
    "County",
    "Zone",
    "MW Capacity",
    "Fuel Type",
]

# Add more ISO-specific fuel mappings here as you refine each clean sheet.
# Format: FUEL_MAPPINGS["ISO_NAME"] = {"raw_value": "standardized_value"}
FUEL_MAPPINGS = {
    "ERCOT": {
        "Solar": "Solar",
        "Wind": "Wind",
        "Gas": "Thermal",
        "Battery": "Storage",
        "Other": "Other",
        "Oil": "Thermal",
        "Nuclear": "Nuclear",
        "Hydro": "Hydro",
    },

    "MISO": {
        "Solar": "Solar",
        "Wind": "Wind",
        "Battery Storage": "Storage",
        "Gas": "Thermal",
        "Coal": "Thermal",
        "Hybrid": "Hybrid",
        "Hydro": "Hydro",
        "Waste Heat Recovery": "Thermal",
        "Diesel": "Thermal",
        "High Voltage DC": "Other",
        "Nuclear": "Nuclear",
        "Biomass": "Thermal",
        "Combined Cycle": "Thermal",
        "Compressed Air Storage": "Storage",
    },

    "ISO-NE": {
        "WND": "Wind",
        "BAT": "Storage",
        "SUN": "Solar",
        "DFO NG": "Thermal",
        "WAT": "Hydro",
        "NUC": "Nuclear",
        "LFG": "Thermal",
        "NG": "Thermal",
        "DFO": "Thermal",
        "KER": "Thermal",
        "WDS": "Thermal",
        "JF KER": "Thermal",
        "NG WO": "Thermal",
        "JF NG": "Thermal",
        "NG RFO": "Thermal",
        "KER NG": "Thermal",
        "JF KER NG": "Thermal",
        "JF": "Thermal",
        "DFO KER": "Thermal",
        "DFO KER NG": "Thermal",
        "BIT": "Thermal",
        "0": "Unknown",
        "NG WDS": "Thermal",
        "BIT RFO": "Thermal",
        "DFO SUB": "Thermal",
        "DFO WDS": "Thermal",
        "WND BAT": "Wind",
        "NG OTH": "Thermal",
        "BLQ DFO KER WDS": "Thermal",
        "MSW": "Thermal",
        "SUN BAT": "Hybrid",
        "FC": "Other",
        "NG SUN BAT": "Hybrid",
        "BLQ WDS": "Thermal",
        "WAT BAT": "Hydro",
        "KER BAT": "Storage",
        "SUN WAT": "Hybrid",
    },

    "PJM": {
        "Storage": "Storage",
        "Solar": "Solar",
        "Natural Gas": "Thermal",
        "Solar, Storage, Hybrid": "Hybrid",
        "Offshore Wind": "Wind",
        "Wind": "Wind",
        "Not Specified": "Unknown",
        "Nuclear": "Nuclear",
        "Wind, Solar, Hybrid": "Hybrid",
        "Natural Gas, Other, Hybrid": "Thermal",
        "Hydro": "Hydro",
        "Natural Gas, Oil, Hybrid": "Thermal",
        "Solar, Wind, Hybrid": "Hybrid",
        "Biomass": "Thermal",
        "Other": "Other",
        "Coal": "Thermal",
        "Oil": "Thermal",
        "Fuel Cell": "Thermal",
    },

    "SPP": {
        "Wind": "Wind",
        "wind": "Wind",
        "Solar": "Solar",
        "Hybrid": "Hybrid",
        "Battery/Storage": "Storage",
        "Thermal": "Thermal",
        "Hydro": "Hydro",
        "Other": "Other",
    },
}
